import { CivicIssue, Person, GraphTriple } from '../types';

export const INITIAL_ISSUES: CivicIssue[] = [
  {
    id: 'issue-1',
    title: 'Overflowing garbage near Main Gate',
    description: 'Waste container near the campus main entrance has been overflowing for 4 days. Attraction of stray animals and foul smell affecting thousands of daily commuters and students.',
    category: 'Garbage',
    location: 'Main Gate, University Campus & AB Road Intersection',
    latitude: 22.7196,
    longitude: 75.8577,
    photo: 'https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&w=800&q=80',
    severity: 'High',
    communityReports: 87,
    peopleAffected: 1284,
    locationsAffected: 14,
    priorityScore: 92,
    status: 'escalated',
    escalationLevel: 'Municipal Corporation',
    createdAt: '2026-09-25T08:30:00Z',
    updatedAt: '2026-09-29T10:15:00Z',
    authority: 'Municipal Corporation',
    progress: 78,
    keywords: ['garbage', 'waste', 'trash', 'main gate', 'overflowing', 'dumping', 'rubbish'],
    mockNodeConnections: {
      peopleCount: 87,
      locationCount: 14,
      affectedCount: 1284,
      authorities: ['College Administration', 'Municipal Corporation Sanitation Wing']
    },
    timeline: [
      { id: 't1', stage: 'reported', label: 'Reported', timestamp: 'Sep 25, 08:30 AM', completed: true, current: false, description: 'Initial report filed by student representative.' },
      { id: 't2', stage: 'confirmed', label: 'Community confirmed', timestamp: 'Sep 25, 11:00 AM', completed: true, current: false, description: '30+ community members confirmed this issue.' },
      { id: 't3', stage: 'priority_reached', label: 'Priority threshold reached', timestamp: 'Sep 26, 02:15 PM', completed: true, current: false, description: 'Score reached 85+. System auto-prioritized.' },
      { id: 't4', stage: 'college_admin', label: 'College administration', timestamp: 'Sep 27, 09:00 AM', completed: true, current: false, description: 'Campus sanitation officer dispatched note.' },
      { id: 't5', stage: 'municipal', label: 'Municipal Corporation', timestamp: 'Sep 28, 04:30 PM', completed: true, current: true, description: 'Escalated to Zonal Sanitation Officer (Ward 12).' },
      { id: 't6', stage: 'action_pending', label: 'Action pending', timestamp: 'Pending', completed: false, current: false, description: 'Truck dispatch scheduled.' },
      { id: 't7', stage: 'resolved', label: 'Resolved', timestamp: 'Pending', completed: false, current: false, description: 'Waste clearance & container replacement.' },
      { id: 't8', stage: 'verified', label: 'Community verified', timestamp: 'Pending', completed: false, current: false, description: 'Neighbor verification required.' }
    ]
  },
  {
    id: 'issue-2',
    title: 'Large pothole near AB Road Entrance',
    description: 'Deep crater on the primary access road near the AB Road turn. Vehicles swerving sharply to avoid it, causing severe bottleneck during peak hours.',
    category: 'Roads',
    location: 'AB Road Entrance, Sector 4',
    latitude: 22.7210,
    longitude: 75.8610,
    photo: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=800&q=80',
    severity: 'High',
    communityReports: 51,
    peopleAffected: 642,
    locationsAffected: 6,
    priorityScore: 81,
    status: 'acknowledged',
    escalationLevel: 'College / Local Admin',
    createdAt: '2026-09-26T10:00:00Z',
    updatedAt: '2026-09-29T11:20:00Z',
    authority: 'College Administration',
    progress: 61,
    keywords: ['pothole', 'road', 'crater', 'asphalt', 'ab road', 'traffic', 'vehicles'],
    mockNodeConnections: {
      peopleCount: 51,
      locationCount: 6,
      affectedCount: 642,
      authorities: ['Public Works Department', 'Campus Facilities']
    },
    timeline: [
      { id: 't1', stage: 'reported', label: 'Reported', timestamp: 'Sep 26, 10:00 AM', completed: true, current: false },
      { id: 't2', stage: 'confirmed', label: 'Community confirmed', timestamp: 'Sep 26, 04:00 PM', completed: true, current: false },
      { id: 't3', stage: 'priority_reached', label: 'Priority threshold reached', timestamp: 'Sep 27, 01:00 PM', completed: true, current: false },
      { id: 't4', stage: 'college_admin', label: 'College administration', timestamp: 'Sep 28, 10:00 AM', completed: true, current: true },
      { id: 't5', stage: 'municipal', label: 'Municipal Corporation', timestamp: 'Pending', completed: false, current: false },
      { id: 't6', stage: 'action_pending', label: 'Action pending', timestamp: 'Pending', completed: false, current: false },
      { id: 't7', stage: 'resolved', label: 'Resolved', timestamp: 'Pending', completed: false, current: false },
      { id: 't8', stage: 'verified', label: 'Community verified', timestamp: 'Pending', completed: false, current: false }
    ]
  },
  {
    id: 'issue-3',
    title: 'Broken streetlights near Hostel Road Pathway',
    description: 'Continuous stretch of 5 streetlights non-functional along the walkway connecting Girl\'s Hostel to the Academic Quad. Safety concern for evening pedestrian traffic.',
    category: 'Streetlights',
    location: 'Hostel Road, West Block Pathway',
    latitude: 22.7180,
    longitude: 75.8540,
    photo: 'https://images.unsplash.com/photo-1509114397022-ed747cca3f65?auto=format&fit=crop&w=800&q=80',
    severity: 'Moderate',
    communityReports: 34,
    peopleAffected: 381,
    locationsAffected: 3,
    priorityScore: 69,
    status: 'confirmed',
    escalationLevel: 'College / Local Admin',
    createdAt: '2026-09-27T14:20:00Z',
    updatedAt: '2026-09-29T09:00:00Z',
    authority: 'College Administration',
    progress: 42,
    keywords: ['streetlight', 'dark', 'light', 'hostel', 'lamp', 'pathway', 'night'],
    mockNodeConnections: {
      peopleCount: 34,
      locationCount: 3,
      affectedCount: 381,
      authorities: ['Electrical Maintenance Dept']
    },
    timeline: [
      { id: 't1', stage: 'reported', label: 'Reported', timestamp: 'Sep 27, 02:20 PM', completed: true, current: false },
      { id: 't2', stage: 'confirmed', label: 'Community confirmed', timestamp: 'Sep 27, 08:30 PM', completed: true, current: true },
      { id: 't3', stage: 'priority_reached', label: 'Priority threshold reached', timestamp: 'Pending', completed: false, current: false },
      { id: 't4', stage: 'college_admin', label: 'College administration', timestamp: 'Pending', completed: false, current: false },
      { id: 't5', stage: 'municipal', label: 'Municipal Corporation', timestamp: 'Pending', completed: false, current: false },
      { id: 't6', stage: 'action_pending', label: 'Action pending', timestamp: 'Pending', completed: false, current: false },
      { id: 't7', stage: 'resolved', label: 'Resolved', timestamp: 'Pending', completed: false, current: false },
      { id: 't8', stage: 'verified', label: 'Community verified', timestamp: 'Pending', completed: false, current: false }
    ]
  },
  {
    id: 'issue-4',
    title: 'Open storm drainage grid near Science Block',
    description: 'Heavy metal drainage cover damaged and missing. Poses severe fall risk for pedestrians and cyclists, especially after dusk.',
    category: 'Drainage',
    location: 'Science Building, East Courtyard',
    latitude: 22.7225,
    longitude: 75.8590,
    photo: 'https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?auto=format&fit=crop&w=800&q=80',
    severity: 'Critical',
    communityReports: 29,
    peopleAffected: 510,
    locationsAffected: 4,
    priorityScore: 76,
    status: 'acknowledged',
    escalationLevel: 'College / Local Admin',
    createdAt: '2026-09-28T09:15:00Z',
    updatedAt: '2026-09-29T12:00:00Z',
    authority: 'College Administration',
    progress: 50,
    keywords: ['drainage', 'drain', 'open drain', 'grate', 'cover', 'science block', 'hazard'],
    mockNodeConnections: {
      peopleCount: 29,
      locationCount: 4,
      affectedCount: 510,
      authorities: ['Civil Engineering Maintenance']
    },
    timeline: [
      { id: 't1', stage: 'reported', label: 'Reported', timestamp: 'Sep 28, 09:15 AM', completed: true, current: false },
      { id: 't2', stage: 'confirmed', label: 'Community confirmed', timestamp: 'Sep 28, 11:30 AM', completed: true, current: false },
      { id: 't3', stage: 'priority_reached', label: 'Priority threshold reached', timestamp: 'Sep 28, 03:00 PM', completed: true, current: false },
      { id: 't4', stage: 'college_admin', label: 'College administration', timestamp: 'Sep 29, 09:00 AM', completed: true, current: true },
      { id: 't5', stage: 'municipal', label: 'Municipal Corporation', timestamp: 'Pending', completed: false, current: false },
      { id: 't6', stage: 'action_pending', label: 'Action pending', timestamp: 'Pending', completed: false, current: false },
      { id: 't7', stage: 'resolved', label: 'Resolved', timestamp: 'Pending', completed: false, current: false },
      { id: 't8', stage: 'verified', label: 'Community verified', timestamp: 'Pending', completed: false, current: false }
    ]
  },
  {
    id: 'issue-5',
    title: 'Contaminated water supply at Library Annex',
    description: 'Drinking water dispenser emitting discolored, murky water with metallic odor. Water coolers turned off temporarily.',
    category: 'Water',
    location: 'Central Library Annex, Ground Floor',
    latitude: 22.7205,
    longitude: 75.8560,
    photo: 'https://images.unsplash.com/photo-1548839140-29a749e1bc4e?auto=format&fit=crop&w=800&q=80',
    severity: 'High',
    communityReports: 43,
    peopleAffected: 890,
    locationsAffected: 5,
    priorityScore: 84,
    status: 'escalated',
    escalationLevel: 'Municipal Corporation',
    createdAt: '2026-09-26T16:45:00Z',
    updatedAt: '2026-09-29T08:30:00Z',
    authority: 'Municipal Corporation',
    progress: 35,
    keywords: ['water', 'dirty water', 'drinking water', 'contamination', 'library', 'pipe'],
    mockNodeConnections: {
      peopleCount: 43,
      locationCount: 5,
      affectedCount: 890,
      authorities: ['Water Supply Department', 'Campus Health Board']
    },
    timeline: [
      { id: 't1', stage: 'reported', label: 'Reported', timestamp: 'Sep 26, 04:45 PM', completed: true, current: false },
      { id: 't2', stage: 'confirmed', label: 'Community confirmed', timestamp: 'Sep 27, 09:00 AM', completed: true, current: false },
      { id: 't3', stage: 'priority_reached', label: 'Priority threshold reached', timestamp: 'Sep 27, 02:00 PM', completed: true, current: false },
      { id: 't4', stage: 'college_admin', label: 'College administration', timestamp: 'Sep 28, 08:30 AM', completed: true, current: false },
      { id: 't5', stage: 'municipal', label: 'Municipal Corporation', timestamp: 'Sep 28, 05:00 PM', completed: true, current: true },
      { id: 't6', stage: 'action_pending', label: 'Action pending', timestamp: 'Pending', completed: false, current: false },
      { id: 't7', stage: 'resolved', label: 'Resolved', timestamp: 'Pending', completed: false, current: false },
      { id: 't8', stage: 'verified', label: 'Community verified', timestamp: 'Pending', completed: false, current: false }
    ]
  },
  {
    id: 'issue-6',
    title: 'Damaged pedestrian crossing signal on North Avenue',
    description: 'Traffic light push button for pedestrians stuck in active position, causing traffic disruption and confusion for pedestrians crossing.',
    category: 'Safety',
    location: 'North Avenue & College Junction',
    latitude: 22.7240,
    longitude: 75.8620,
    photo: 'https://images.unsplash.com/photo-1508873696983-2df515122519?auto=format&fit=crop&w=800&q=80',
    severity: 'Moderate',
    communityReports: 19,
    peopleAffected: 310,
    locationsAffected: 2,
    priorityScore: 58,
    status: 'reported',
    escalationLevel: 'Community',
    createdAt: '2026-09-28T18:10:00Z',
    updatedAt: '2026-09-29T07:40:00Z',
    authority: 'Municipal Corporation',
    progress: 20,
    keywords: ['pedestrian', 'signal', 'traffic light', 'north avenue', 'crossing', 'safety'],
    mockNodeConnections: {
      peopleCount: 19,
      locationCount: 2,
      affectedCount: 310,
      authorities: ['Traffic Management Bureau']
    },
    timeline: [
      { id: 't1', stage: 'reported', label: 'Reported', timestamp: 'Sep 28, 06:10 PM', completed: true, current: true },
      { id: 't2', stage: 'confirmed', label: 'Community confirmed', timestamp: 'Pending', completed: false, current: false },
      { id: 't3', stage: 'priority_reached', label: 'Priority threshold reached', timestamp: 'Pending', completed: false, current: false },
      { id: 't4', stage: 'college_admin', label: 'College administration', timestamp: 'Pending', completed: false, current: false },
      { id: 't5', stage: 'municipal', label: 'Municipal Corporation', timestamp: 'Pending', completed: false, current: false },
      { id: 't6', stage: 'action_pending', label: 'Action pending', timestamp: 'Pending', completed: false, current: false },
      { id: 't7', stage: 'resolved', label: 'Resolved', timestamp: 'Pending', completed: false, current: false },
      { id: 't8', stage: 'verified', label: 'Community verified', timestamp: 'Pending', completed: false, current: false }
    ]
  },
  {
    id: 'issue-7',
    title: 'Clogged sewage line overflowing on Student Mall Walkway',
    description: 'Sewage overflow on main brick pavement path outside student cafeteria. High health concern.',
    category: 'Drainage',
    location: 'Student Mall, Quadrangle',
    latitude: 22.7215,
    longitude: 75.8580,
    photo: 'https://images.unsplash.com/photo-1621451537084-482c73073a0f?auto=format&fit=crop&w=800&q=80',
    severity: 'High',
    communityReports: 62,
    peopleAffected: 1100,
    locationsAffected: 8,
    priorityScore: 88,
    status: 'action_started',
    escalationLevel: 'Municipal Corporation',
    createdAt: '2026-09-25T11:00:00Z',
    updatedAt: '2026-09-29T14:10:00Z',
    authority: 'Municipal Corporation',
    progress: 70,
    keywords: ['sewage', 'clogged', 'overflow', 'drainage', 'student mall', 'cafeteria'],
    mockNodeConnections: {
      peopleCount: 62,
      locationCount: 8,
      affectedCount: 1100,
      authorities: ['Municipal Sewerage Dept', 'Campus Public Health']
    },
    timeline: [
      { id: 't1', stage: 'reported', label: 'Reported', timestamp: 'Sep 25, 11:00 AM', completed: true, current: false },
      { id: 't2', stage: 'confirmed', label: 'Community confirmed', timestamp: 'Sep 25, 03:00 PM', completed: true, current: false },
      { id: 't3', stage: 'priority_reached', label: 'Priority threshold reached', timestamp: 'Sep 26, 10:00 AM', completed: true, current: false },
      { id: 't4', stage: 'college_admin', label: 'College administration', timestamp: 'Sep 26, 02:00 PM', completed: true, current: false },
      { id: 't5', stage: 'municipal', label: 'Municipal Corporation', timestamp: 'Sep 27, 09:30 AM', completed: true, current: false },
      { id: 't6', stage: 'action_pending', label: 'Action started', timestamp: 'Sep 28, 01:00 PM', completed: true, current: true, description: 'Suction tanker deployed.' },
      { id: 't7', stage: 'resolved', label: 'Resolved', timestamp: 'Pending', completed: false, current: false },
      { id: 't8', stage: 'verified', label: 'Community verified', timestamp: 'Pending', completed: false, current: false }
    ]
  },
  {
    id: 'issue-8',
    title: 'Unlit pedestrian tunnel under Railway Bridge',
    description: 'Passageway lighting completely dead. Deep shadows make evening travel unsafe for commuters and university staff walking home.',
    category: 'Safety',
    location: 'Railway Underpass, East Gate',
    latitude: 22.7170,
    longitude: 75.8630,
    photo: 'https://images.unsplash.com/photo-1517649763962-0c623266ddc0?auto=format&fit=crop&w=800&q=80',
    severity: 'Critical',
    communityReports: 48,
    peopleAffected: 750,
    locationsAffected: 5,
    priorityScore: 89,
    status: 'escalated',
    escalationLevel: 'Municipal Corporation',
    createdAt: '2026-09-24T19:30:00Z',
    updatedAt: '2026-09-29T08:15:00Z',
    authority: 'Municipal Corporation',
    progress: 65,
    keywords: ['dark', 'tunnel', 'railway', 'unlit', 'safety', 'lights', 'underpass'],
    mockNodeConnections: {
      peopleCount: 48,
      locationCount: 5,
      affectedCount: 750,
      authorities: ['Railway Infrastructure & Municipal Lighting']
    },
    timeline: [
      { id: 't1', stage: 'reported', label: 'Reported', timestamp: 'Sep 24, 07:30 PM', completed: true, current: false },
      { id: 't2', stage: 'confirmed', label: 'Community confirmed', timestamp: 'Sep 25, 08:00 AM', completed: true, current: false },
      { id: 't3', stage: 'priority_reached', label: 'Priority threshold reached', timestamp: 'Sep 26, 04:00 PM', completed: true, current: false },
      { id: 't4', stage: 'college_admin', label: 'College administration', timestamp: 'Sep 27, 11:00 AM', completed: true, current: false },
      { id: 't5', stage: 'municipal', label: 'Municipal Corporation', timestamp: 'Sep 28, 10:00 AM', completed: true, current: true },
      { id: 't6', stage: 'action_pending', label: 'Action pending', timestamp: 'Pending', completed: false, current: false },
      { id: 't7', stage: 'resolved', label: 'Resolved', timestamp: 'Pending', completed: false, current: false },
      { id: 't8', stage: 'verified', label: 'Community verified', timestamp: 'Pending', completed: false, current: false }
    ]
  },
  {
    id: 'issue-9',
    title: 'Vandalized bus shelter seating at South Campus stop',
    description: 'Benches broken and metal frame bent outwards. Commuters and elderly visitors forced to stand in heat.',
    category: 'Public Property',
    location: 'Bus Stand #3, South Campus',
    latitude: 22.7150,
    longitude: 75.8550,
    photo: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=800&q=80',
    severity: 'Low',
    communityReports: 15,
    peopleAffected: 210,
    locationsAffected: 1,
    priorityScore: 45,
    status: 'reported',
    escalationLevel: 'Community',
    createdAt: '2026-09-27T16:00:00Z',
    updatedAt: '2026-09-29T10:00:00Z',
    authority: 'Municipal Corporation',
    progress: 10,
    keywords: ['bus stop', 'bench', 'vandalized', 'bus shelter', 'seating', 'public property'],
    mockNodeConnections: {
      peopleCount: 15,
      locationCount: 1,
      affectedCount: 210,
      authorities: ['Public Transport Infrastructure']
    },
    timeline: [
      { id: 't1', stage: 'reported', label: 'Reported', timestamp: 'Sep 27, 04:00 PM', completed: true, current: true },
      { id: 't2', stage: 'confirmed', label: 'Community confirmed', timestamp: 'Pending', completed: false, current: false },
      { id: 't3', stage: 'priority_reached', label: 'Priority threshold reached', timestamp: 'Pending', completed: false, current: false },
      { id: 't4', stage: 'college_admin', label: 'College administration', timestamp: 'Pending', completed: false, current: false },
      { id: 't5', stage: 'municipal', label: 'Municipal Corporation', timestamp: 'Pending', completed: false, current: false },
      { id: 't6', stage: 'action_pending', label: 'Action pending', timestamp: 'Pending', completed: false, current: false },
      { id: 't7', stage: 'resolved', label: 'Resolved', timestamp: 'Pending', completed: false, current: false },
      { id: 't8', stage: 'verified', label: 'Community verified', timestamp: 'Pending', completed: false, current: false }
    ]
  },
  {
    id: 'issue-10',
    title: 'Rusted playground swing set in Community Park',
    description: 'Support chain broken on public park swings. Successfully fixed by Parks Maintenance crew and verified by local residents.',
    category: 'Public Property',
    location: 'Central Civic Park, Sector 2',
    latitude: 22.7230,
    longitude: 75.8520,
    photo: 'https://images.unsplash.com/photo-1564429238817-393bd4286b2d?auto=format&fit=crop&w=800&q=80',
    severity: 'Low',
    communityReports: 8,
    peopleAffected: 95,
    locationsAffected: 1,
    priorityScore: 32,
    status: 'resolved',
    escalationLevel: 'College / Local Admin',
    createdAt: '2026-09-20T11:00:00Z',
    updatedAt: '2026-09-28T16:00:00Z',
    authority: 'College Administration',
    progress: 100,
    keywords: ['park', 'swing', 'playground', 'rusted', 'children', 'repaired'],
    mockNodeConnections: {
      peopleCount: 8,
      locationCount: 1,
      affectedCount: 95,
      authorities: ['Parks & Recreation Board']
    },
    timeline: [
      { id: 't1', stage: 'reported', label: 'Reported', timestamp: 'Sep 20, 11:00 AM', completed: true, current: false },
      { id: 't2', stage: 'confirmed', label: 'Community confirmed', timestamp: 'Sep 21, 02:00 PM', completed: true, current: false },
      { id: 't3', stage: 'priority_reached', label: 'Priority threshold reached', timestamp: 'Sep 22, 10:00 AM', completed: true, current: false },
      { id: 't4', stage: 'college_admin', label: 'College administration', timestamp: 'Sep 23, 09:00 AM', completed: true, current: false },
      { id: 't5', stage: 'municipal', label: 'Municipal Corporation', timestamp: 'N/A', completed: false, current: false },
      { id: 't6', stage: 'action_pending', label: 'Action completed', timestamp: 'Sep 27, 03:00 PM', completed: true, current: false },
      { id: 't7', stage: 'resolved', label: 'Resolved', timestamp: 'Sep 28, 11:00 AM', completed: true, current: false },
      { id: 't8', stage: 'verified', label: 'Community verified', timestamp: 'Sep 28, 04:00 PM', completed: true, current: true }
    ]
  }
];

export const MOCK_PEOPLE: Person[] = [
  { id: 'p1', name: 'Aarav Sharma', role: 'Student Resident', avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80' },
  { id: 'p2', name: 'Priya Patel', role: 'Campus Commuter', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80' },
  { id: 'p3', name: 'Rohan Gupta', role: 'Faculty Member', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80' },
  { id: 'p4', name: 'Sneha Kulkarni', role: 'Local Business Owner', avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=150&q=80' }
];

export const MOCK_GRAPH_TRIPLES: GraphTriple[] = [
  { source: 'Person: Aarav Sharma', relation: 'reported', target: 'Problem: Overflowing garbage near Main Gate' },
  { source: 'Person: Priya Patel', relation: 'supports', target: 'Problem: Overflowing garbage near Main Gate' },
  { source: 'Person: Rohan Gupta', relation: 'affected_by', target: 'Problem: Overflowing garbage near Main Gate' },
  { source: 'Problem: Overflowing garbage near Main Gate', relation: 'located_at', target: 'Location: Main Gate' },
  { source: 'Problem: Overflowing garbage near Main Gate', relation: 'affects', target: 'Community: 1,284 Residents & Commuters' },
  { source: 'Problem: Overflowing garbage near Main Gate', relation: 'escalated_to', target: 'Authority: Municipal Corporation' },
  { source: 'Authority: Municipal Corporation', relation: 'responsible_for', target: 'Problem: Overflowing garbage near Main Gate' }
];
